// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "edee69cc-058f-4089-bab3-9bc84da955ea";

const char SSID[]               = "TOAD";    // Network SSID (name)
const char PASS[]               = "qaywsxedc1234";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "2vp@Thgnm?6iO@s8A4Py8O2Hs";    // Secret device password

void onEsstischPLChange();
void onFlurSChange();
void onKuecheLEDObenChange();
void onKuecheLEDUntenChange();
void onKuechePLChange();

CloudDimmedLight esstisch_PL;
CloudDimmedLight flur_S;
CloudDimmedLight kueche_LED_Oben;
CloudDimmedLight kueche_LED_Unten;
CloudDimmedLight kueche_PL;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(esstisch_PL, READWRITE, ON_CHANGE, onEsstischPLChange);
  ArduinoCloud.addProperty(flur_S, READWRITE, ON_CHANGE, onFlurSChange);
  ArduinoCloud.addProperty(kueche_LED_Oben, READWRITE, ON_CHANGE, onKuecheLEDObenChange);
  ArduinoCloud.addProperty(kueche_LED_Unten, READWRITE, ON_CHANGE, onKuecheLEDUntenChange);
  ArduinoCloud.addProperty(kueche_PL, READWRITE, ON_CHANGE, onKuechePLChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
